-- 21_puebla_presidentes.sql — presidentes municipales (2024-2027). PARCIAL: ~191 de 217.
-- Falta la cola Y-Z (WebFetch trunca la página). Correr la verificación para listar
-- los faltantes y completarlos por cvegeo.
-- Fuente: Wikipedia "Anexo:Presidentes municipales de Puebla (2024-2027)". Verificar.
-- PSI = Pacto Social de Integración (partido local). FPM = Fuerza por México.

begin;

create temp table tmp_pm (nom text, name text, party text);

insert into tmp_pm (nom, name, party) values
  ('Acajete','Cristian Flores Flores','MORENA'),
  ('Acateno','Diego Torre Osorio','PVEM'),
  ('Acatlán','Gudalupe Lucero Bárcenas','MORENA'),
  ('Acatzingo','Germán Coleote Jiménez','MORENA'),
  ('Acteopan','René Castillo Guzmán','PSI'),
  ('Ahuacatlán','Miguel Villalba Cabrera','PT'),
  ('Ahuatlán','Baldomero Lezama León','MORENA'),
  ('Ahuazotepec','Alfredo Ramírez Hernández','PRD'),
  ('Ahuehuetitla','Marbella Pilar Tlatelpa Bravo','PT'),
  ('Ajalpan','Faustino Soriano Centeno','PT'),
  ('Albino Zertuche','Rosa Isabel Cardoso Ortiz','MORENA'),
  ('Aljojuca','Guadalupe Lara Estévez','PVEM'),
  ('Altepexi','Juan González Juárez','MC'),
  ('Amixtlán','Blanca Estela Juárez Becerra','PRD'),
  ('Amozoc','José Severiano de la Rosa Romero','MORENA'),
  ('Aquixtla','Amando Nava Arroyo','MORENA'),
  ('Atempan','Fausto Moreno Salazar','Fuerza por México'),
  ('Atexcal','Rigoberto González Mendiola','PAN'),
  ('Atlequizayan','Bertha Rodríguez Rodríguez','PRI'),
  ('Atlixco','Ariadna Ayala Camarillo','PT'),
  ('Atoyatempan','Elías Noé Juárez López','MC'),
  ('Atzala','Verónica Nolasco Tufiño','MORENA'),
  ('Atzitzihuacán','Jaime Arellano Carrillo','Fuerza por México'),
  ('Atzitzintla','Eduardo Velázquez Medina','PRD'),
  ('Axutla','Cecilio Gerardo Ballinas Aguilar','PT'),
  ('Ayotoxco de Guerrero','Alicia Guerrero Hernández','MORENA'),
  ('Calpan','Vicente Sánchez Méndez','MORENA'),
  ('Caltepec','Guillermo Negrellos Romualdo','Fuerza por México'),
  ('Camocuautla','Marisela Vázquez García','PRI'),
  ('Caxhuacán','Silverio Santiago Castañeda','MORENA'),
  ('Coatepec','Norma Angélica Márquez Jiménez','MORENA'),
  ('Coatzingo','Abel Chávez Orea','PVEM'),
  ('Cohetzala','Héctor Guzmán Nájera','MC'),
  ('Cohuecán','Octavio Martínez Aragón','PAN'),
  ('Coronango','Armando Filemón Aguirre Amaro','PT'),
  ('Coxcatlán','Camerino Montalvo Montiel','PRI'),
  ('Coyomeapan','Guillermo Abasolo Romaña','PVEM'),
  ('Coyotepec','Víctor Martínez Barrera','PVEM'),
  ('Cuapiaxtla de Madero','Sandra Sánchez Ramos','MORENA'),
  ('Cuautempan','Gerardo Cortés Caballero','PT'),
  ('Cuautinchán','José Luis González Hernández','Independiente'),
  ('Cuautlancingo','Omar Alberto Muñoz Alfaro','MORENA'),
  ('Cuayuca de Andrade','Lorena Castillo López','PT'),
  ('Cuetzalan del Progreso','Oscar Paula Cruz','PVEM'),
  ('Cuyoaco','Iván Conrado Camacho Romero','PRI'),
  ('Chalchicomula de Sesma','José Guadalupe Méndez Rocha','MC'),
  ('Chapulco','Marcelino Martínez Cuevas','PAN'),
  ('Chiautla','Gonzalo Oropeza García','PT'),
  ('Chiautzingo','María del Carmen Palestino Cordero','MORENA'),
  ('Chiconcuautla','Roque Morales Iturbide','PRI'),
  ('Chichiquila','Jesús Hernández López','PAN'),
  ('Chietla','Edgardo Ponce Cortés','PVEM'),
  ('Chigmecatitlán','María Celofas Flores Acevedo','PRI'),
  ('Chignahuapan','Juan Rivera Trejo','MORENA'),
  ('Chignautla','Juan Toral Ramos','Nueva Alianza'),
  ('Chila','María Teresa Rosas Andrade','MORENA'),
  ('Chila de la Sal','Fernando Amigón Romero','MORENA'),
  ('Honey','Alberto Ordaz González','MC'),
  ('Chilchotla','Miguel Argüello Sandoval','PVEM'),
  ('Chinantla','María del Carmen Domínguez Fortozo','Fuerza por México'),
  ('Domingo Arenas','Álvaro Botello Munive','Nueva Alianza'),
  ('Eloxochitlán','Delfino Hernández Hernández','PT'),
  ('Epatlán','Raúl Merino Badillo','Fuerza por México'),
  ('Esperanza','Isaac Rodríguez Ochoa','MORENA'),
  ('Francisco Z. Mena','Víctor Vargas García','PRD'),
  ('General Felipe Ángeles','Javier de Jesús Vera','PVEM'),
  ('Guadalupe','Anahí Yosenia Herrera Martínez','PVEM'),
  ('Guadalupe Victoria','María Fernanda Romero Solís','PVEM'),
  ('Hermenegildo Galeana','José Manuel Rodríguez Cruz','PAN'),
  ('Huaquechula','Raúl Marín Espinoza','PRI'),
  ('Huatlatlauca','Javier Vázquez Rodríguez','MORENA'),
  ('Huauchinango','Rogelio López Angulo','Nueva Alianza'),
  ('Huehuetla','Georgina del Carmen Paulino Díaz','PRI'),
  ('Huehuetlán el Chico','María Guadalupe Espinoza Sánchez','PRI'),
  ('Huejotzingo','Roberto Solís Valles','MORENA'),
  ('Hueyapan','Alfonso Lino Pozos','PRI'),
  ('Hueytamalco','Edgar Iván Luna Rivera','PT'),
  ('Hueytlalpan','Reynaldo González Ramos','PRI'),
  ('Huitzilan de Serdán','Josué Elías Velázquez Bonilla','PRI'),
  ('Huitziltepec','Iván Rojas Cortés','Nueva Alianza'),
  ('Ixcamilpa de Guerrero','Delia García','PSI'),
  ('Ixcaquixtla','Salvador Castillo Miranda','PRI'),
  ('Ixtacamaxtitlán','Moisés Juárez Peña','PRI'),
  ('Ixtepec','César Hilario Guzmán Vázquez','PRI'),
  ('Izúcar de Matamoros','Eliseo Morales Rosales','PVEM'),
  ('Jalpan','Freddy Galindo Márquez','MORENA'),
  ('Jolalpan','Hesiquio Valdez González','PAN'),
  ('Jonotla','Jael Peña Lobato','Nueva Alianza'),
  ('Jopala','Fabio Becerra Méndez','MC'),
  ('Juan C. Bonilla','José Cinto Bernal','PVEM'),
  ('Juan Galindo','Maximino Muñoz Vázquez','PRI'),
  ('Juan N. Méndez','Guillermo Gregorio del Rosario','MORENA'),
  ('Lafragua','Charvel Hernández Argüello','PVEM'),
  ('Libres','Mario Díaz Hernández','PVEM'),
  ('La Magdalena Tlatlauquitepec','Ernestina Jiménez Torres','MORENA'),
  ('Mazapiltepec de Juárez','Miguel Pérez Cuellar','PVEM'),
  ('Mixtla','Tomás González Yáñez','MORENA'),
  ('Molcaxac','Roberto Parada Coto','Fuerza por México'),
  ('Cañada Morelos','Ana Laura Sánchez Benítez','PRI'),
  ('Naupan','Valerio Escorcia Calva','MORENA'),
  ('Nauzontla','Maricela Ramiro Juárez','PAN'),
  ('Nealtican','Imelda Gil Osorio','PT'),
  ('Nicolás Bravo','Rubén Tepole Huerta','PRI'),
  ('Nopalucan','Norberto Saldaña Amador','PT'),
  ('Ocotepec','Roberto Romero Hernández','Nueva Alianza'),
  ('Ocoyucan','Aristóteles Campos Flores','PAN'),
  ('Olintla','Abdi Abihud Ramírez Pérez','PRI'),
  ('Oriental','Fidel Flores Concha','MORENA'),
  ('Pahuatlán','Eduardo Romero Romero','PT'),
  ('Palmar de Bravo','Juan Carlos Varillas Lima','Independiente'),
  ('Pantepec','Araceli Gaspar Cruz','MORENA'),
  ('Petlalcingo','Isabel Vergara Tapia','PRI'),
  ('Piaxtla','Miguel Ángel Maceda Carrera','PT'),
  ('Puebla','José Chedraui Budib','MORENA'),
  ('Quecholac','María Guadalupe Martínez Gerardo','PSI'),
  ('Quimixtlán','José Martínez Pimentel','PVEM'),
  ('Rafael Lara Grajales','Horacio Castillo López','PT'),
  ('Los Reyes de Juárez','Alfonso Vélez Merino','MORENA'),
  ('San Andrés Cholula','Guadalupe Cuautle Torres','PAN'),
  ('San Antonio Cañada','Areli González Hernández','PRI'),
  ('San Diego La Mesa Tochimiltzingo','Juan Hernández Torres','PVEM'),
  ('San Felipe Teotlalcingo','Néstor Cortés González','PAN'),
  ('San Felipe Tepatlán','Luis Ángel Dávila Santos','PRD'),
  ('San Gabriel Chilac','Jorge Alberto Lezama Martínez','PT'),
  ('San Gregorio Atzompa','Carlos Minutti Precoma','PSI'),
  ('San Jerónimo Tecuanipan','Máximo Aponte Téllez','PVEM'),
  ('San Jerónimo Xayacatlán','Johan Alberto Muñoz','MORENA'),
  ('San José Chiapa','Alejandro Hernández Romero','PRD'),
  ('San José Miahuatlán','Zoilo Noél Guzmán Herrera','MORENA'),
  ('San Juan Atenco','José Mayko de Lázaro Urbina','MORENA'),
  ('San Juan Atzompa','Victoria Guadalupe Tobanche Macías','PRI'),
  ('San Martín Texmelucan','Juan Manuel Alonso Ramírez','PT'),
  ('San Martín Totoltepec','Gloria Bravo García','MORENA'),
  ('San Matías Tlalancaleca','Óscar Anguiano Martínez','PAN'),
  ('San Miguel Ixitlán','Lilimar Meza Reyes','PRI'),
  ('San Miguel Xoxtla','Guadalupe Ortiz Pérez','PVEM'),
  ('San Nicolás Buenos Aires','Victoria Sánchez Pérez','MC'),
  ('San Nicolás de los Ranchos','Juan Panohaya Cuahutitla','Nueva Alianza'),
  ('San Pablo Anicano','Lluvia de Nieve Cuadrado Galeano','PRI'),
  ('San Pedro Cholula','Tonantzin Fernández Díaz','MORENA'),
  ('San Pedro Yeloixtlahuaca','Albino Solís Ambrosio','Nueva Alianza'),
  ('San Salvador el Seco','Yareli Orato Vélez','PVEM'),
  ('San Salvador el Verde','José Gregorio Ojeda Ojeda','PT'),
  ('San Salvador Huixcolotla','Manuel Alejandro Porras Florentino','PT'),
  ('San Sebastián Tlacotepec','Raymundo Atanacio Arciga','PVEM'),
  ('Santa Catarina Tlaltempan','Javier de los Santos Rosas','Fuerza por México'),
  ('Santa Inés Ahuatempan','Edith Villa Trujillo','PRI'),
  ('Santa Isabel Cholula','Adrián Flores Ramírez','PSI'),
  ('Santiago Miahuatlán','Omar Eulogio Toledo Balderas','PVEM'),
  ('Santo Tomás Hueyotlipan','María Guadalupe López Zavaleta','MORENA'),
  ('Soltepec','Eligio Barrales González','PT'),
  ('Tecali de Herrera','Alan Gilberth Amador Gómez','MORENA'),
  ('Tecamachalco','Mateo Hernández López','MORENA'),
  ('Tecomatlán','Avelino Cándido Rivera Campos','PRI'),
  ('Tehuacán','Alejandro Barroso Chávez','MORENA'),
  ('Tehuitzingo','Jorge Estrada Gervacio','PAN'),
  ('Tenampulco','Juan Carlos Escalona Pérez','PRI'),
  ('Teopantlán','Ricardo Espinoza Pérez','MORENA'),
  ('Teotlalco','Javier Sánchez Espinoza','PRI'),
  ('Tepanco de López','Alejandro Martínez Carrera','Nueva Alianza'),
  ('Tepango de Rodríguez','Dagoberto Galindo Galindo','PT'),
  ('Tepatlaxco de Hidalgo','Julio González Bonilla','MORENA'),
  ('Tepeaca','Julián Alfredo Velázquez Romero','MORENA'),
  ('Tepemaxalco','Arturo Díaz Pérez','PSI'),
  ('Tepeojuma','Gustavo Leoncio Sánchez Martiñón','PRI'),
  ('Tepetzintla','Nazario Zempoalteco Rubio','PRI'),
  ('Tepexco','Salvador Mejía Cortés','PSI'),
  ('Tepexi de Rodríguez','Humberto Bolaños del Rosario','MORENA'),
  ('Tepeyahualco','Saíd de Jesús Godos Luna','MC'),
  ('Tepeyahualco de Cuauhtémoc','Abigail Hernández Huerta','Fuerza por México'),
  ('Tetela de Ocampo','Óscar Méndez Díaz','PRD'),
  ('Teteles de Ávila Castillo','Saúl Márquez Viveros','Fuerza por México'),
  ('Teziutlán','Karla Victoria Martínez Gallegos','MORENA'),
  ('Tianguismanalco','Juan Pérez Moral','MORENA'),
  ('Tilapa','Juan José Flores de la Torre','PSI'),
  ('Tlacotepec','Martín de Jesús Camargo de la Peña','PRD'),
  ('Tlacuilotepec','Alejandro Josué Guzmán García','PVEM'),
  ('Tlachichuca','Carmelo Amador Fuentes Bailón','MC'),
  ('Tlahuapan','Rosiceli Díaz Hernández','PRI'),
  ('Tlaltenango','José Luis Hinorosa Ramírez','PSI'),
  ('Tlanepantla','Lino Romero Posadas','MORENA'),
  ('Tlaola','Simón Garrido Morgado','PAN'),
  ('Tlapacoya','Omar Herrero Reyes','Fuerza por México'),
  ('Tlapanalá','Silverio Galicia Baltazar','PRI'),
  ('Tlatlauquitepec','Juan Manuel Téllez Salazar','MORENA'),
  ('Tlaxco','Juan Neri Licona','PVEM'),
  ('Tochimilco','David Reyes González Calyeca','Nueva Alianza'),
  ('Tochtepec','Dinorah Carolina Aguilar Flores','MORENA'),
  ('Totoltepec de Guerrero','Edgardo Santos Catarino','Nueva Alianza'),
  ('Tulcingo','Marubet Meza Rodríguez','MORENA'),
  ('Tuzamapan de Galeana','Blaz González Hernández','PVEM'),
  ('Tzicatlacoyan','Pedro Romero Coriche','PT'),
  ('Venustiano Carranza','Marco Valencia Ávila','PAN'),
  ('Vicente Guerrero','Efraín Ginéz González','PAN'),
  ('Xayacatlán de Bravo','Maximino Domínguez Herrera','Nueva Alianza'),
  ('Xicotepec','Carlos Barragán Amador','MORENA'),
  ('Xicotlán','Alberto Cayetano Morales Ramos','PAN'),
  ('Xiutetelco','Alicia Guerrero Hernández','MORENA');

insert into public.representatives (role, cve_ent, cvegeo_mun, name, party)
select 'municipal_president', '21', m.cvegeo, t.name, t.party
from tmp_pm t
join public.municipalities m
  on replace(upper(translate(trim(m.nom_mun), 'áéíóúüÁÉÍÓÚÜñÑ', 'aeiouuAEIOUUnN')),' ','')
   = replace(upper(translate(trim(t.nom),     'áéíóúüÁÉÍÓÚÜñÑ', 'aeiouuAEIOUUnN')),' ','')
 and m.cve_ent = '21'
on conflict (role, cve_ent, coalesce(cvegeo_mun,''), coalesce(distrito,-1))
do update set name = excluded.name, party = excluded.party;

commit;

-- Verificación: municipios de Puebla sin presidente (incluye la cola Y-Z faltante).
select m.cvegeo, m.nom_mun
from public.municipalities m
where m.cve_ent = '21'
  and not exists (select 1 from public.representatives r
                  where r.role='municipal_president' and r.cvegeo_mun = m.cvegeo)
order by m.nom_mun;
