-- 30_veracruz_presidentes.sql — presidentes municipales (2026-2029). PARCIAL ~178/212.
-- Falta la cola Villa Aldama->Zozocolco + algunos intermedios (correr verificación).
-- Fuente: Wikipedia "Anexo:Presidentes municipales de Veracruz (2026-2029)". Verificar.
-- Periodo 2026-2029 (tomaron protesta 1-ene-2026). Cambios de partido -> partido vigente.

begin;

create temp table tmp_pm (nom text, name text, party text);

insert into tmp_pm (nom, name, party) values
  ('Acajete','María Claudia Nava Santos','MC'),
  ('Acatlán','Nahum Rogelio Hernández Grajales','PVEM'),
  ('Acayucan','Raúl David Salomón García','MORENA'),
  ('Actopan','José Eduardo Utrera Carreto','MORENA'),
  ('Acula','Filiberto Sánchez Martínez','PVEM'),
  ('Acultzingo','Daniel González Amaro','PT'),
  ('Camarón de Tejeda','Susana Guadalupe Ameca Parissi','MORENA'),
  ('Alpatláhuac','Alejandro Alfonso Camarillo','PAN'),
  ('Alto Lucero de Gutiérrez Barrios','Roque Castillo Castillo','MORENA'),
  ('Altotonga','Juan Pablo Becerra Hernández','MORENA'),
  ('Alvarado','Alberto Ángel Cobos Márquez','PVEM'),
  ('Amatitlán','Horacio Aguirre Galo','MORENA'),
  ('Naranjos Amatlán','Humberto Ancelin Cruz','PT'),
  ('Amatlán de los Reyes','Concepción Guillermina Méndez López','MORENA'),
  ('Ángel R. Cabada','Samantha Sánchez del Hoyo','MORENA'),
  ('La Antigua','Venancio Carlos Reyes Bretón','MC'),
  ('Apazapan','Midori Yoana Cardeña Santamaría','PT'),
  ('Aquila','María Petra Alonso Vázquez','PVEM'),
  ('Astacinga','Jannet Sitlali Itehua Jiménez','PAN'),
  ('Atlahuilco','Marcelino Tlaxcala Tlaxcala','MORENA'),
  ('Atoyac','Juan Carlos Rojas Castro','PAN'),
  ('Atzacan','Israel Raymundo Solano Jiménez','MC'),
  ('Atzalan','José Homero Domínguez Landa','PRI'),
  ('Tlaltetela','María de Jesús Caballero López','MORENA'),
  ('Ayahualulco','Claudia Liliana Castillo Pimentel','MORENA'),
  ('Banderilla','Arnulfo Rodríguez González','PAN'),
  ('Benito Juárez','Edvino Hernández Hernández','PVEM'),
  ('Boca del Río','María Josefina Gamboa Torales','PAN'),
  ('Calcahualco','Israel Sandoval Frías','MC'),
  ('Camerino Z. Mendoza','Gustavo Sánchez Ortiz','PT'),
  ('Carrillo Puerto','Teresa Itzel Jacomé Mora','PRI'),
  ('Catemaco','Norberto Eduardo Toscano','MC'),
  ('Cazones de Herrera','Humberto Olvera Torres','MC'),
  ('Cerro Azul','Fernando Hernández Spinoso','MORENA'),
  ('Citlaltépetl','Ángel de Jesús del Ángel Olivares','PRI'),
  ('Coacoatzintla','Juan Solano Landa','MORENA'),
  ('Coahuitlán','Isaac García Álvarez','PRI'),
  ('Coatepec','Jorge Ignacio Luna Hernández','MORENA'),
  ('Coatzacoalcos','Pedro Miguel Rosaldo García','MORENA'),
  ('Coatzintla','Jorge Adrián Alanís Monterrubio','MORENA'),
  ('Coetzala','Geremías Nereo Apale Tehuintle','MC'),
  ('Colipa','Jacobo Masegosa Llanas','MORENA'),
  ('Comapa','Nora Jessica Lagunes Jaúregui','PAN'),
  ('Córdoba','Manuel Alonso Cerezo','MORENA'),
  ('Cosamaloapan de Carpio','Jorge Alberto Villegas Cázares','MORENA'),
  ('Cosautlán de Carvajal','Pablo Martínez Ortiz','MORENA'),
  ('Coscomatepec','José Benjamín Armando Reyes Muñoz','MC'),
  ('Cosoleacaque','Cirilo Vázquez Parissi','PRI'),
  ('Cotaxtla','Martín Flores Soto','MORENA'),
  ('Coxquihui','Lauro Becerra García','PAN'),
  ('Coyutla','Yamuri Emmanuel Palacio Aldana','PVEM'),
  ('Cuichapa','Fernando Hernández Martínez','MORENA'),
  ('Cuitláhuac','Angélica Peña Martínez','MORENA'),
  ('Chacaltianguis','Akciel Jamir Torrecilla Torrecilla','PT'),
  ('Chalma','Jilly Edson Argüelles Martínez','MC'),
  ('Chiconamel','María Luisa Bautista Hernández','PVEM'),
  ('Chiconquiaco','Nazario Emmanuel Perea Morales','PVEM'),
  ('Chicontepec','Noé Torres Martínez','PRI'),
  ('Chinameca','Santiago Cortés Padua','PRI'),
  ('Chinampa de Gorostiza','Baltazar Avendaño Delgado','PT'),
  ('Las Choapas','Jesús Uribe Esquivel','MORENA'),
  ('Chocamán','María Isabel Figueroa Luna','PAN'),
  ('Chontla','José Luis Ponce Zaleta','PRI'),
  ('Chumatlán','Josué Sánchez Salazar','MORENA'),
  ('Emiliano Zapata','Daniel Antonio Baizabal González','MORENA'),
  ('Espinal','Viridiana Pérez Patiño','PVEM'),
  ('Filomeno Mata','Miguel Ventura Cortés','PAN'),
  ('Fortín','Alfonso Efraín Marín Delfín','MC'),
  ('Gutiérrez Zamora','Carlos Raúl Silva Vega','PAN'),
  ('Hidalgotitlán','Floricela Antonio Sánchez','MORENA'),
  ('Huatusco','Alberto Urcino Méndez Gálvez','PAN'),
  ('Huayacocotla','Araceli Monroy Razo','MORENA'),
  ('Hueyapan de Ocampo','Armando Ramón Calderas Ríos','MORENA'),
  ('Huiloapan de Cuauhtémoc','Héctor Omar Urbano Dávila','MC'),
  ('Ignacio de la Llave','María de la Luz Santiago Ponce','PVEM'),
  ('Ilamatlán','Yuridia Inés Santiago Gopar','PVEM'),
  ('Isla','Ramón Martínez Tress','MC'),
  ('Ixcatepec','Obed Melgoza Matías','PAN'),
  ('Ixhuacán de los Reyes','José Luis Vargas González','PRI'),
  ('Ixhuatlán del Café','Viridiana Bretón Feito','PAN'),
  ('Ixhuatlancillo','José Manuel González Nicolás','PT'),
  ('Ixhuatlán del Sureste','Raúl González Martínez','MC'),
  ('Ixhuatlán de Madero','Héctor Norberto Aguirre Ibarrola','MORENA'),
  ('Ixmatlahuacan','Celia Fabián García','PAN'),
  ('Ixtaczoquitlán','José Luis Cortés Gutiérrez','MORENA'),
  ('Jalacingo','Miguel Vicente Cuellar Contreras','MORENA'),
  ('Xalapa','Daniela Guadalupe Griego Ceballos','MORENA'),
  ('Jalcomulco','Roberto Ixtla Campuzano','MC'),
  ('Jáltipan','Gildardo Maldonado Guzmán','MC'),
  ('Jamapa','Reynaldo Fernández Ortiz','MORENA'),
  ('Jesús Carranza','Ranferi Plata Rodríguez','MORENA'),
  ('Xico','Eduardo Pozos Pérez','MORENA'),
  ('Jilotepec','José Roberto Marcelo Cortés','MC'),
  ('Juan Rodríguez Clara','Irineo Mauleón Elvira','MORENA'),
  ('Juchique de Ferrer','Juan Martín González Gumecindo','PAN'),
  ('Landero y Coss','Pedro Domínguez García','PRI'),
  ('Lerdo de Tejada','Flor María de Jesús Sosa Zamudio','MORENA'),
  ('Magdalena','Olga Zepahua Tlecuile','MORENA'),
  ('Maltrata','Néstor Toral Pérez','MC'),
  ('Manlio Fabio Altamirano','Yuliana Neva Quirazco','PT'),
  ('Mariano Escobedo','Baldomero Montiel Esteves','PT'),
  ('Martínez de la Torre','Modesto Velázquez Toral','MORENA'),
  ('Mecatlán','Miguel Vázquez Antonio','MORENA'),
  ('Mecayapan','Tomás González Hernández','MC'),
  ('Medellín de Bravo','Samuel Acosta Martínez','PVEM'),
  ('Miahuatlán','Javier Bárcena Villa','MC'),
  ('Minatitlán','Guillermo Reyes Espronceda','MORENA'),
  ('Misantla','René Omar Jaén Domínguez','MC'),
  ('Mixtla de Altamirano','Celia García Rodríguez','PRI'),
  ('Moloacán','Eleazar Alcántara Martínez','MORENA'),
  ('Naolinco','José Narciso Reyes Aguilar','PAN'),
  ('Naranjal','Francisco Florentino Tepepa Miranda','PRI'),
  ('Nautla','Felipe Nicolás Capitaine Rivera','MC'),
  ('Nogales','Libni Zuriel de la Cruz Cruz','PT'),
  ('Oluta','Jesús Manuel Garduza Salcedo','PAN'),
  ('Omealca','Dionisio Herrera Torres','PAN'),
  ('Orizaba','Hugo Chahin Kuri','PRI'),
  ('Otatitlán','Víctor Manuel Porragas Mortera','MC'),
  ('Oteapan','Noé Gómez Pérez','MC'),
  ('Ozuluama de Mascareñas','Jorge Luis del Ángel Delgado','MORENA'),
  ('Pajapan','José Luis González Hernández','MORENA'),
  ('Pánuco','Mayra Anel Delgado Castillo','MORENA'),
  ('Papantla','Gonzalo Flores Castellanos','MORENA'),
  ('Paso del Macho','Sergio Ángel Velázquez Rivera','MC'),
  ('Paso de Ovejas','Uriel Peralta Barrios','MC'),
  ('La Perla','Miguel Ángel Bautista García','PAN'),
  ('Perote','Vinicio Ascencio Fernández','PRI'),
  ('Platón Sánchez','Margarita del Ángel Vera','PT'),
  ('Playa Vicente','Ramiro Martínez Amezcua','PVEM'),
  ('Poza Rica de Hidalgo','Janeth Adanely Rodriguez Rodriguez','MORENA'),
  ('Pueblo Viejo','María de los Ángeles Hernández Rodríguez','MORENA'),
  ('Puente Nacional','Bibiana Sánchez Báez','MC'),
  ('Rafael Delgado','Miguel Ángel Sánchez Arcadio','PRI'),
  ('Rafael Lucio','Juan Hernández Rodríguez','MORENA'),
  ('Los Reyes','Lucas Eduardo Ajactle Cueyactle','PRI'),
  ('Río Blanco','José Antonio May González','PAN'),
  ('Saltabarranca','Elvis Laureani Román','MORENA'),
  ('San Andrés Tenejapan','Domingo Cereso Cruz','MC'),
  ('San Andrés Tuxtla','Rafael Gustavo Fararoni Magaña','PVEM'),
  ('San Juan Evangelista','Eloisa Zetina Gómez','PVEM'),
  ('Santiago Tuxtla','Noé Domínguez Cadena','MORENA'),
  ('Sayula de Alemán','José Manuel Muñoz Murrieta','PT'),
  ('Soconusco','Cristóbal Sinforoso Rosas','MC'),
  ('Soledad Atzompa','Romeo Rosales Crisóstomo','PRI'),
  ('Soledad de Doblado','Elsa Cruz Méndez Ibarra','PVEM'),
  ('Soteapan','Sósimo López Ramírez','MC'),
  ('Tamalín','Bolivia Patricio del Ángel','MORENA'),
  ('Tamiahua','María del Pilar Guzmán Medellín','PVEM'),
  ('Tampico Alto','Adrián Domínguez Rangel','PVEM'),
  ('Tancoco','Víctor Victoriano Vidaurri','MC'),
  ('Tantima','María Guadalupe Santos Cenobio','MORENA'),
  ('Tantoyuca','Roberto Francisco San Román Solana','MORENA'),
  ('Tatatila','Moisés Cruz Ortiz','PT'),
  ('Tecolutla','Wenceslao Santiago Castro','PVEM'),
  ('Tehuipango','Juan Quiahua Panzo','PAN'),
  ('Tempoal','Martín Meráz Argüelles','MORENA'),
  ('Tenampa','Carlos Sánchez Reyes','PVEM'),
  ('Tenochtitlán','Fernando Sánchez Hernández','PVEM'),
  ('Teocelo','Daniela Villegas Olmos','PT'),
  ('Tepatlaxco','Erika Jaúregui Hernández','PAN'),
  ('Tepetlán','Valente Aguilar Hinojosa','PT'),
  ('Tepetzintla','Olga Isela Gerardo Morales','PAN'),
  ('Tequila','Javier Missael García Zepahua','MORENA'),
  ('José Azueta','José Antonio Bello Ramírez','PVEM'),
  ('Texcatepec','Fidel Alonso Mauricio','PAN'),
  ('Texhuacán','Miguel Juan Cuaquehua Quechulpa','MC'),
  ('Texistepec','Julissa Millán Díaz','PT'),
  ('Tezonapa','Omar Paz Morán','MORENA'),
  ('Tierra Blanca','Edwing Eduardo González Fernández','MORENA'),
  ('Tihuatlán','Raúl Hernández Gallardo','MC'),
  ('Tlacojalpan','Gertrudis Domínguez Vargas','PT'),
  ('Tlacolulan','Abel Hernández Hernández','MORENA'),
  ('Tlacotalpan','Christian Romero Pérez','MORENA'),
  ('Tlacotepec de Mejía','Ansberto Marino Espinoza Murillo','PAN'),
  ('Tlachichilco','Oscar Herrera Pérez','PAN'),
  ('Tlalixcoyan','Bertha Adriana Lagunes Sánchez','MORENA'),
  ('Tlalnelhuayocan','Arianna Guadalupe Ángeles Aguirre','PRI'),
  ('Tlapacoyan','Miguel Ángel Cervantes Córdoba','PAN'),
  ('Tlaquilpa','Alfredo Tentzohua Hernández','PRI'),
  ('Tlilapan','Germain Tiburcio Aguas','PT'),
  ('Tomatlán','Nicolás Prado Morales','PAN'),
  ('Tonayán','Servando Hernández Aguilera','MC'),
  ('Totutla','Ubaldo Odilón Pérez Vallejo','PT'),
  ('Tuxpan','Daniel Cortina Martínez','MORENA'),
  ('Tuxtilla','Bertha Reyes Solano','PVEM'),
  ('Úrsulo Galván','Bertín Bravo Montero','MC'),
  ('Vega de Alatorre','Felipe Mata Barradas','PT'),
  ('Veracruz','Rosa María Hernández Espejo','MORENA');

insert into public.representatives (role, cve_ent, cvegeo_mun, name, party)
select 'municipal_president', '30', m.cvegeo, t.name, t.party
from tmp_pm t
join public.municipalities m
  on replace(upper(translate(trim(m.nom_mun), 'áéíóúüÁÉÍÓÚÜñÑ', 'aeiouuAEIOUUnN')),' ','')
   = replace(upper(translate(trim(t.nom),     'áéíóúüÁÉÍÓÚÜñÑ', 'aeiouuAEIOUUnN')),' ','')
 and m.cve_ent = '30'
on conflict (role, cve_ent, coalesce(cvegeo_mun,''), coalesce(distrito,-1))
do update set name = excluded.name, party = excluded.party;

commit;

-- Verificación: municipios de Veracruz sin presidente (la cola Villa Aldama->Zozocolco
-- y posibles nombres INEGI largos). Pásamelos para cerrarlos.
select m.cvegeo, m.nom_mun
from public.municipalities m
where m.cve_ent = '30'
  and not exists (select 1 from public.representatives r
                  where r.role='municipal_president' and r.cvegeo_mun = m.cvegeo)
order by m.nom_mun;
