-- diputados_federales.sql — diputados federales de mayoría relativa.
-- Generado por build_diputados_federales.py desde el xlsx oficial de la Cámara.
-- Solo MR (con distrito); plurinominales omitidos.

insert into public.representatives (role, cve_ent, distrito, name, party) values
  ('federal_deputy','01',1,'Ambriz Delgadillo Humberto','PRI'),
  ('federal_deputy','01',2,'Becerra Moreno Monica','PAN'),
  ('federal_deputy','01',3,'Martínez López Paulo Gonzalo','PAN'),
  ('federal_deputy','02',1,'Ruiz López Alma Laura','MORENA'),
  ('federal_deputy','02',2,'Sánchez Arredondo Nancy Guadalupe','MORENA'),
  ('federal_deputy','02',3,'Moreno Ramírez Claudia Lisbeth','MORENA'),
  ('federal_deputy','02',4,'López Gorosave Rocío','MORENA'),
  ('federal_deputy','02',5,'Sánchez Rodelo Karla Patricia','MORENA'),
  ('federal_deputy','02',6,'Herrera Solórzano Gilberto','MORENA'),
  ('federal_deputy','02',7,'Fernández Samaniego José Armando','MORENA'),
  ('federal_deputy','02',8,'Gallardo García Fausto','PVEM'),
  ('federal_deputy','02',9,'Brown Figueredo Hilda Araceli','MORENA'),
  ('federal_deputy','03',1,'González Bareño Juan Carlos','PVEM'),
  ('federal_deputy','03',2,'Díaz Luis Armando','PT'),
  ('federal_deputy','04',1,'Castillo Quintana Elda Esther del Carmen','MORENA'),
  ('federal_deputy','04',2,'Basto González Gabriela del Carmen','MORENA'),
  ('federal_deputy','05',1,'Moreno Hernández Brígido Ramiro','PT'),
  ('federal_deputy','05',2,'Borrego Adame Francisco Javier','MORENA'),
  ('federal_deputy','05',3,'Kalionchiz De la Fuente Theodoros','PAN'),
  ('federal_deputy','05',4,'Abramo Masso Yerico','PRI'),
  ('federal_deputy','05',5,'Anaya Llamas José Guillermo','PAN'),
  ('federal_deputy','05',6,'Cuevas Sánchez Cintia','MORENA'),
  ('federal_deputy','05',7,'Castro Villarreal Antonio Lorenzo','MORENA'),
  ('federal_deputy','05',8,'Licerio Valdes Hilda Magdalena','PVEM'),
  ('federal_deputy','06',1,'Morán Sánchez Leoncio Alfonso','MORENA'),
  ('federal_deputy','06',2,'Valencia de la Mora Gricelda','MORENA'),
  ('federal_deputy','07',1,'Alegría Gómez José Miguel','PT'),
  ('federal_deputy','07',2,'del Río Zenteno Karina Margarita','MORENA'),
  ('federal_deputy','07',3,'Vázquez Vázquez Alfredo','MORENA'),
  ('federal_deputy','07',4,'Zebadúa Alva Joaquín','MORENA'),
  ('federal_deputy','07',5,'Ramírez Guzmán Emilio Ramón','MORENA'),
  ('federal_deputy','07',6,'Esponda Torres Flor de María','MORENA'),
  ('federal_deputy','07',7,'Arreola Trinidad Azucena','MORENA'),
  ('federal_deputy','07',8,'Albores Gleason Roberto Armando','PT'),
  ('federal_deputy','07',9,'Santiago Rodríguez Guillermo Rafael','MORENA'),
  ('federal_deputy','07',10,'Gonzalez Flandez Deliamaria','PVEM'),
  ('federal_deputy','07',11,'Moreno Villatoro Rosario del Carmen','MORENA'),
  ('federal_deputy','07',12,'Urbina Castañeda Rosa Irene','MORENA'),
  ('federal_deputy','07',13,'Villatoro Osorio Jorge Luis','PVEM'),
  ('federal_deputy','08',1,'Murguía Lardizábal Daniel','MORENA'),
  ('federal_deputy','08',2,'Vargas Meraz Teresita de Jesús','MORENA'),
  ('federal_deputy','08',3,'Aguilar Gil Lilia','PT'),
  ('federal_deputy','08',4,'Pérez Cuéllar Alejandro','PVEM'),
  ('federal_deputy','08',5,'Meléndez Ortega Juan Antonio','PRI'),
  ('federal_deputy','08',6,'Granados Trespalacios María Angélica','PAN'),
  ('federal_deputy','08',7,'Corral Ordóñez Jesús Roberto','PT'),
  ('federal_deputy','08',8,'Domínguez Domínguez César Alejandro','PRI'),
  ('federal_deputy','08',9,'Chávez Velázquez Noel','PRI'),
  ('federal_deputy','09',1,'Álvarez López Jesús Emiliano','MORENA'),
  ('federal_deputy','09',2,'Benavides Castañeda José Alberto','PT'),
  ('federal_deputy','09',3,'Jiménez Godoy Gabriela Georgina','MORENA'),
  ('federal_deputy','09',4,'Padierna Luna María de los Dolores','MORENA'),
  ('federal_deputy','09',5,'Perea Cruz Jesús Irugami','MORENA'),
  ('federal_deputy','09',6,'Campos Plancarte Daniel','MORENA'),
  ('federal_deputy','09',7,'Rendón Gómez Juan Guillermo','MORENA'),
  ('federal_deputy','09',8,'Silva Andraca Ruth Maricela','PVEM'),
  ('federal_deputy','09',9,'Mejía Méndez Roberto','MORENA'),
  ('federal_deputy','09',10,'Zavala Gómez del Campo Margarita Ester','PAN'),
  ('federal_deputy','09',11,'Segura Trejo Elena Edith','MORENA'),
  ('federal_deputy','09',12,'Sandoval Hernández Mónica Elizabeth','PRI'),
  ('federal_deputy','09',13,'Sánchez Cervantes Francisco Javier','MORENA'),
  ('federal_deputy','09',14,'Hernández Mirón Carlos','MORENA'),
  ('federal_deputy','09',15,'Döring Casar Federico','PAN'),
  ('federal_deputy','09',16,'Piceno Navarro Estela Carina','MORENA'),
  ('federal_deputy','09',17,'Madrazo Silva Carlos Arturo','PVEM'),
  ('federal_deputy','09',18,'García Hernández Gabriel','MORENA'),
  ('federal_deputy','09',19,'Téllez Hernández Héctor Saúl','PAN'),
  ('federal_deputy','09',20,'Rojo Pimentel Ana Karina','PT'),
  ('federal_deputy','09',21,'Garcés Medina Edén','MORENA'),
  ('federal_deputy','09',22,'Zúñiga Cerón Marisela','MORENA'),
  ('federal_deputy','10',1,'García Vidaña Martha Olivia','MORENA'),
  ('federal_deputy','10',2,'Del Valle Ramírez Alejandra','MORENA'),
  ('federal_deputy','10',3,'Villarreal Solis Gerardo','PVEM'),
  ('federal_deputy','10',4,'Jiménez Delgado Silvia Patricia','PAN'),
  ('federal_deputy','11',1,'Sánchez Sánchez Luis Gerardo','PRI'),
  ('federal_deputy','11',2,'De la Vega Vargas Alma Rosa','MORENA'),
  ('federal_deputy','11',3,'Torres Graciano Fernando','PAN'),
  ('federal_deputy','11',4,'Estrada Domínguez Francisco Javier','MORENA'),
  ('federal_deputy','11',5,'Ramírez Barba Éctor Jaime','PAN'),
  ('federal_deputy','11',6,'Márquez Alcalá Laura Cristina','PAN'),
  ('federal_deputy','11',7,'Gutiérrez Valtierra Diana Estefanía','PAN'),
  ('federal_deputy','11',8,'Prieto Gallardo Ernesto Alejandro','MORENA'),
  ('federal_deputy','11',9,'Rodríguez Barroso Diego Angel','PAN'),
  ('federal_deputy','11',10,'Calderón Díaz Alejandro','MORENA'),
  ('federal_deputy','11',11,'Salim Alle Miguel Ángel','PAN'),
  ('federal_deputy','11',12,'Rosales Cruz María Magdalena','MORENA'),
  ('federal_deputy','11',13,'Higareda Segura Lucero','MORENA'),
  ('federal_deputy','11',14,'Acosta Trujillo Juana','MORENA'),
  ('federal_deputy','11',15,'Aguirre Gallardo José Javier','MORENA'),
  ('federal_deputy','12',1,'Mora Eguiluz Celeste','MORENA'),
  ('federal_deputy','12',2,'Domínguez Serna Yoloczin Lizbeth','MORENA'),
  ('federal_deputy','12',3,'Cabrera Lagunas Ma. del Carmen','PVEM'),
  ('federal_deputy','12',4,'Taja Ramírez Javier','MORENA'),
  ('federal_deputy','12',5,'Olivares Mejía Gerardo','PT'),
  ('federal_deputy','12',6,'Nava García María del Carmen','PVEM'),
  ('federal_deputy','12',7,'Sánchez Barrios Carlos','MORENA'),
  ('federal_deputy','12',8,'De La Mora Torreblanca Marco Antonio','PVEM'),
  ('federal_deputy','13',1,'Andrade Zurutuza Daniel','MORENA'),
  ('federal_deputy','13',2,'Salomón Durán Ciria Yamile','PVEM'),
  ('federal_deputy','13',3,'P. Ángeles Moreno Tatiana Tonantzin','MORENA'),
  ('federal_deputy','13',4,'De La Vega Sánchez Alma Lidia','MORENA'),
  ('federal_deputy','13',5,'Cornejo Gómez Astrit Viridiana','MORENA'),
  ('federal_deputy','13',6,'Crespo Arroyo Ricardo','MORENA'),
  ('federal_deputy','13',7,'Rubio Sánchez Mirna María de la Luz','MORENA'),
  ('federal_deputy','14',1,'Guízar Macías Francisco Javier','PT'),
  ('federal_deputy','14',2,'Gómez Villalobos Tecutli José Guadalupe','MC'),
  ('federal_deputy','14',3,'Iñiguez Franco José Mario','PAN'),
  ('federal_deputy','14',4,'Álvarez Villaseñor Raúl','MORENA'),
  ('federal_deputy','14',5,'Blancas Mercado Bruno','MORENA'),
  ('federal_deputy','14',6,'Carranza Gómez Beatriz','MORENA'),
  ('federal_deputy','14',7,'García Hernández Claudia','MORENA'),
  ('federal_deputy','14',8,'Espinosa Sánchez Paola Milagros','PAN'),
  ('federal_deputy','14',9,'Castellanos Polanco Favio','MORENA'),
  ('federal_deputy','14',10,'Borboa Becerra Omar Antonio','PAN'),
  ('federal_deputy','14',11,'Gómez Pozos Merilyn','MORENA'),
  ('federal_deputy','14',12,'González Pérez Sandra Beatriz','MORENA'),
  ('federal_deputy','14',13,'Sánchez González José Luis','PT'),
  ('federal_deputy','14',14,'Michel López Marcela','MORENA'),
  ('federal_deputy','14',15,'Vázquez Jiménez Alonso de Jesús','PAN'),
  ('federal_deputy','14',16,'Maldonado Chavarín Alberto','MORENA'),
  ('federal_deputy','14',17,'Ramírez Ramos Antonio de Jesús','PVEM'),
  ('federal_deputy','14',18,'Arreola Lopez Haidyd','MORENA'),
  ('federal_deputy','14',19,'Cárdenas Galván Clara','MORENA'),
  ('federal_deputy','14',20,'Castillo Lozano Katia Alejandra','MORENA'),
  ('federal_deputy','15',1,'Mendoza Mondragón María Luisa','PVEM'),
  ('federal_deputy','15',2,'Vázquez García Dionicia','MORENA'),
  ('federal_deputy','15',3,'Castillo Gabino Diana','PT'),
  ('federal_deputy','15',4,'Carrasco Godínez Melva','MORENA'),
  ('federal_deputy','15',5,'Galindo Alarcón Patricia','PT'),
  ('federal_deputy','15',6,'Villalpando Riquelme Julieta','MORENA'),
  ('federal_deputy','15',7,'Zagal Ramírez Xóchitl Nashielly','MORENA'),
  ('federal_deputy','15',8,'Beltrán Reyes Anay','MORENA'),
  ('federal_deputy','15',9,'Marin Rangel Ivan','MORENA'),
  ('federal_deputy','15',10,'Vilchis Contreras Luis Fernando','PT'),
  ('federal_deputy','15',11,'Arzola Vargas Xóchitl Teresa','MORENA'),
  ('federal_deputy','15',12,'Corona Arvizu Armando','MORENA'),
  ('federal_deputy','15',13,'Navarrete Rivera Alma Delia','MORENA'),
  ('federal_deputy','15',14,'Garfias Alcantara Claudia Leticia','MORENA'),
  ('federal_deputy','15',15,'Anaya Martínez Josefina','MORENA'),
  ('federal_deputy','15',16,'Manzanilla Téllez Emilio','PT'),
  ('federal_deputy','15',17,'Aguilera Claro Zaria','MORENA'),
  ('federal_deputy','15',18,'Sánchez Juárez Claudia','PVEM'),
  ('federal_deputy','15',19,'Valdepeñas González Gabriela','MORENA'),
  ('federal_deputy','15',20,'Ruiz Páez Montserrat','MORENA'),
  ('federal_deputy','15',21,'Millán Contreras Iván','MORENA'),
  ('federal_deputy','15',22,'Moya Bastón Martha Amalia','PAN'),
  ('federal_deputy','15',23,'Hernández Pérez José Luis','PVEM'),
  ('federal_deputy','15',24,'Durán Reveles José Luis','PVEM'),
  ('federal_deputy','15',25,'Avilés Domínguez Leide','MORENA'),
  ('federal_deputy','15',26,'Miranda Barrera Luis Enrique','PVEM'),
  ('federal_deputy','15',27,'Santiago Pineda Wblester','PT'),
  ('federal_deputy','15',28,'Domínguez Rodríguez Roberto Ángel','MORENA'),
  ('federal_deputy','15',29,'Ulloa Pérez Gerardo','MORENA'),
  ('federal_deputy','15',30,'Hernández Pérez César Agustín','MORENA'),
  ('federal_deputy','15',31,'Bautista Bravo Juan Angel','MORENA'),
  ('federal_deputy','15',32,'Martínez Ventura Luis Enrique','PT'),
  ('federal_deputy','15',33,'de la Rosa León María Guadalupe','MORENA'),
  ('federal_deputy','15',34,'Álvarez Nemer Mónica Angélica','MORENA'),
  ('federal_deputy','15',35,'Hernández Tapia Arturo Roberto','MORENA'),
  ('federal_deputy','15',36,'Varela Domínguez Juan Carlos','MORENA'),
  ('federal_deputy','15',37,'Zenteno Santaella Pedro Mario','MORENA'),
  ('federal_deputy','15',38,'Cuanalo Araujo Jesús Martín','PVEM'),
  ('federal_deputy','15',39,'Montalvo Luna José Luis','PT'),
  ('federal_deputy','15',40,'Huerta Romero Azucena','PVEM'),
  ('federal_deputy','16',1,'Godoy Rangel Leonel','MORENA'),
  ('federal_deputy','16',2,'Cruz Lucatero José Luis','MORENA'),
  ('federal_deputy','16',3,'Bernal Martínez Mary Carmen','PT'),
  ('federal_deputy','16',4,'Ortega Tiburcio Rosa Guadalupe','MORENA'),
  ('federal_deputy','16',5,'Shember Domínguez Delhi Miroslava','MORENA'),
  ('federal_deputy','16',6,'Téllez Marín José Luis','PT'),
  ('federal_deputy','16',7,'Velázquez Vázquez Marcela','MORENA'),
  ('federal_deputy','16',8,'Núñez Aguilar Ernesto','PVEM'),
  ('federal_deputy','16',9,'Mendoza Arias Guadalupe Araceli','IND'),
  ('federal_deputy','16',10,'Cortés Mendoza David Alejandro','PAN'),
  ('federal_deputy','16',11,'López Carrillo Vanessa','PT'),
  ('federal_deputy','17',1,'Anaya Villegas Sandra','MORENA'),
  ('federal_deputy','17',2,'Barrera Vázquez Ariadna','MORENA'),
  ('federal_deputy','17',3,'Winkler Trujillo Cindy','PVEM'),
  ('federal_deputy','17',4,'Flores Bustamante Juan Ángel','MORENA'),
  ('federal_deputy','17',5,'Alonso Gutiérrez Agustín','MORENA'),
  ('federal_deputy','18',1,'Porras Baylón Any Marilú','MORENA'),
  ('federal_deputy','18',2,'Navarro Pérez Beatriz Andrea','MORENA'),
  ('federal_deputy','18',3,'Ortiz Rodríguez Jorge Armando','PT'),
  ('federal_deputy','19',1,'Niño de Rivera Vela Homero Ricardo','PAN'),
  ('federal_deputy','19',2,'Cantú Ramírez Andrés Mauricio','PRI'),
  ('federal_deputy','19',3,'Palacios Medina Sandra Patricia','MORENA'),
  ('federal_deputy','19',4,'Zamora Ramírez Elisa Paola','PAN'),
  ('federal_deputy','19',5,'González Soto Santiago','PT'),
  ('federal_deputy','19',6,'Gómez Cárdenas Annia Sarahí','PAN'),
  ('federal_deputy','19',7,'Guevara Garza Carlos Alberto','PVEM'),
  ('federal_deputy','19',8,'Quiroz Gallegos Adriana Belinda','MORENA'),
  ('federal_deputy','19',9,'Espinoza Eguía Juan Francisco','PRI'),
  ('federal_deputy','19',10,'González González Ana Isabel','PRI'),
  ('federal_deputy','19',11,'Garza de la Garza Samantha Margarita','PAN'),
  ('federal_deputy','19',12,'de la Garza Villarreal Héctor Alfonso','PVEM'),
  ('federal_deputy','19',13,'Quiroga Treviño Luis Orlando','PVEM'),
  ('federal_deputy','19',14,'Gloria López José','PT'),
  ('federal_deputy','20',1,'Vázquez Ruíz Miriam de los Angeles','MORENA'),
  ('federal_deputy','20',2,'Juan Carlos Irma','MORENA'),
  ('federal_deputy','20',3,'García García Margarita','PT'),
  ('federal_deputy','20',4,'Jiménez Vásquez Naty Poob Pijy','MORENA'),
  ('federal_deputy','20',5,'Antonio Altamirano Carol','MORENA'),
  ('federal_deputy','20',6,'López Sánchez José Alejandro','PT'),
  ('federal_deputy','20',7,'Sánchez López Gloria','MORENA'),
  ('federal_deputy','20',8,'Bolaños-Cacho Cué Raúl','PVEM'),
  ('federal_deputy','20',9,'Bautista Peláez María del Carmen','MORENA'),
  ('federal_deputy','20',10,'Cruz Mendoza Carmelo','MORENA'),
  ('federal_deputy','21',1,'Santander Soto Gissel','MORENA'),
  ('federal_deputy','21',2,'Cruz Peláez Fatima Almendra','PVEM'),
  ('federal_deputy','21',3,'Reyes Cabrera Norma Sirley','MORENA'),
  ('federal_deputy','21',4,'González Hernández Juan Antonio','MORENA'),
  ('federal_deputy','21',5,'García Romero Rafaela Vianey','MORENA'),
  ('federal_deputy','21',6,'Carvajal Hidalgo Alejandro','MORENA'),
  ('federal_deputy','21',7,'Rivera Vivanco Claudia','MORENA'),
  ('federal_deputy','21',8,'Mier Bañuelos Carlos Ignacio','MORENA'),
  ('federal_deputy','21',9,'Gali López José Antonio','PVEM'),
  ('federal_deputy','21',10,'Pérez Popoca María Fabiola Karina','MORENA'),
  ('federal_deputy','21',11,'López Ruíz José Antonio','PT'),
  ('federal_deputy','21',12,'Merino Escamilla Nora Yessica','PT'),
  ('federal_deputy','21',13,'Carrillo Cubillas Mario Miguel','MORENA'),
  ('federal_deputy','21',14,'Castillo López Eduardo','MORENA'),
  ('federal_deputy','21',15,'Orozco Caballero María del Rosario','MORENA'),
  ('federal_deputy','21',16,'Alatriste Cantú Adolfo','PVEM'),
  ('federal_deputy','22',1,'Herrera Ruiz Gilberto','MORENA'),
  ('federal_deputy','22',2,'Astudillo Suárez Ricardo','PVEM'),
  ('federal_deputy','22',3,'García Jimeno Alcocer Ma. Lorena','PAN'),
  ('federal_deputy','22',4,'Sosa Pichardo Roberto','PAN'),
  ('federal_deputy','22',5,'Calzada Mercado Mario','PRI'),
  ('federal_deputy','22',6,'Fernández Fuentes Luis Humberto','MORENA'),
  ('federal_deputy','23',1,'Carrillo Soberanis Juan Luis','PVEM'),
  ('federal_deputy','23',2,'Villegas Canché Freyda Marybel','MORENA'),
  ('federal_deputy','23',3,'Aldana Navarro Luis Humberto','MORENA'),
  ('federal_deputy','23',4,'Ávila Vera Mildred Concepción','MORENA'),
  ('federal_deputy','24',1,'Velazco Bautista Aremy','MORENA'),
  ('federal_deputy','24',2,'Fernández Martínez José Luis','PVEM'),
  ('federal_deputy','24',3,'Bautista Villegas Oscar','PVEM'),
  ('federal_deputy','24',4,'Castillo Morales Francisco Adrián','MORENA'),
  ('federal_deputy','24',5,'Azuara Zúñiga David','PAN'),
  ('federal_deputy','24',6,'Valladares Eichelmann Juan Carlos','PVEM'),
  ('federal_deputy','24',7,'García Antonio Briceyda','MORENA'),
  ('federal_deputy','25',1,'Domínguez Nava Graciela (LICENCIA)','MORENA'),
  ('federal_deputy','25',2,'Ayala Leyva Ana Elizabeth','MORENA'),
  ('federal_deputy','25',3,'García Hernández Jesús Fernando','PT'),
  ('federal_deputy','25',4,'Pompa Robles Felicita','MORENA'),
  ('federal_deputy','25',5,'Ibarra Ramos Jesús Alfonso','MORENA'),
  ('federal_deputy','25',6,'Carrazco Macías Olegaria','MORENA'),
  ('federal_deputy','25',7,'Villegas Sánchez Merary','MORENA'),
  ('federal_deputy','26',1,'Baldenebro Arredondo Manuel de Jesús','MORENA'),
  ('federal_deputy','26',2,'Pujol Irastorza Jesús Antonio','MORENA'),
  ('federal_deputy','26',3,'Barreras Samaniego Diana Karina','PT'),
  ('federal_deputy','26',4,'Flores Robles Ramón Angel','PT'),
  ('federal_deputy','26',5,'Mendoza Ruiz Jacobo','MORENA'),
  ('federal_deputy','26',6,'Acosta Islas Anabel','MORENA'),
  ('federal_deputy','26',7,'Higuera Esquer Alma Manuela','MORENA'),
  ('federal_deputy','27',1,'Gutiérrez Bocanegra Julio Ernesto','MORENA'),
  ('federal_deputy','27',2,'Peña Vidal Iván','MORENA'),
  ('federal_deputy','27',3,'Graniel Zenteno Rosa Margarita','MORENA'),
  ('federal_deputy','27',4,'Lastra Bastar Jaime Humberto','MORENA'),
  ('federal_deputy','27',5,'Milland Pérez Beatriz','MORENA'),
  ('federal_deputy','27',6,'Mollinedo Cano Tey','MORENA'),
  ('federal_deputy','28',1,'Canturosas Villarreal Carlos Enrique','PVEM'),
  ('federal_deputy','28',2,'Hernández Sáenz Claudia Alejandra','MORENA'),
  ('federal_deputy','28',3,'De Los Santos Flores Casandra Prisilla','PVEM'),
  ('federal_deputy','28',4,'López Hernández Mario Alberto','PVEM'),
  ('federal_deputy','28',5,'Braña Mojica José','PVEM'),
  ('federal_deputy','28',6,'Narro Panameño Blanca Araceli','MORENA'),
  ('federal_deputy','28',7,'Elizondo Guerra Olga Juliana','PT'),
  ('federal_deputy','28',8,'Nader Nasrallah Jesús Antonio','PAN'),
  ('federal_deputy','29',1,'Aguilar López José Alejandro','PT'),
  ('federal_deputy','29',2,'Vázquez Conchas Raymundo (LICENCIA)','MORENA'),
  ('federal_deputy','29',3,'Garay Loredo Irma Yordana','PT'),
  ('federal_deputy','30',1,'Guzmán González Denisse','PVEM'),
  ('federal_deputy','30',2,'Cervantes de la Cruz Elizabeth','MORENA'),
  ('federal_deputy','30',3,'Armenta Oliveros Magaly','MORENA'),
  ('federal_deputy','30',4,'Vera Maria del Rosario','PAN'),
  ('federal_deputy','30',5,'Velázquez Vallejo Francisco Javier','MORENA'),
  ('federal_deputy','30',6,'Pérez Bernabe Jaime Humberto','MORENA'),
  ('federal_deputy','30',7,'Herrera Villavicencio Mónica','MORENA'),
  ('federal_deputy','30',8,'Mier Acolt Jorge Alberto','MORENA'),
  ('federal_deputy','30',9,'González Naveda Adrián','PT'),
  ('federal_deputy','30',10,'Ferráez Centeno Ana Miriam','MORENA'),
  ('federal_deputy','30',11,'Villegas García Isidro Enrique','MORENA'),
  ('federal_deputy','30',12,'Villacis Palacios Zoraya','MORENA'),
  ('federal_deputy','30',13,'Hernández Rodríguez Blanca Estela','PVEM'),
  ('federal_deputy','30',14,'Ramírez Cisneros Jessica','MORENA'),
  ('federal_deputy','30',15,'Villegas Guarneros Dulce María Corina','MORENA'),
  ('federal_deputy','30',16,'Escobar García Zenyazen Roberto','MORENA'),
  ('federal_deputy','30',17,'Corro Mendoza Margarita','MORENA'),
  ('federal_deputy','30',18,'Puertos Chimalhua Jonathan','PVEM'),
  ('federal_deputy','30',19,'Tenorio Adame Paola','MORENA'),
  ('federal_deputy','31',1,'Barrera Puc Rocío Natalí','MORENA'),
  ('federal_deputy','31',2,'Sánchez Reyes Jorge Luis','MORENA'),
  ('federal_deputy','31',3,'Brito Zapata Oscar Iván','MORENA'),
  ('federal_deputy','31',4,'Rodríguez Heredia María Isabel','PAN'),
  ('federal_deputy','31',5,'Villanueva Moo Jazmín Yaneli','MORENA'),
  ('federal_deputy','31',6,'Saiden Quiroz Jessica','MORENA'),
  ('federal_deputy','32',1,'Luévano Cantú María Soledad','MORENA'),
  ('federal_deputy','32',2,'Olguín Serna Julia Arcelia','MORENA'),
  ('federal_deputy','32',3,'Mejía Haro Ulises','MORENA'),
  ('federal_deputy','32',4,'del Muro García Ana Luisa','PT')
on conflict (role, cve_ent, coalesce(cvegeo_mun,''), coalesce(distrito,-1))
do update set name = excluded.name, party = excluded.party;
